#!/bin/bash

deepspeed --include localhost:0,1 --master_port 25642 llava/train/train_mem.py \
    --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 1e-5 \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path /public/home/renwu04/fmy/LLaVA-PruMerge-text/checkpoints/llava-v1.5-7b-Qformer-11-lora-finetune_from_vicuna-proto-mlp-2-4-layers-all-tokens-merge \
    --version v1 \
    --data_path /public/home/renwu04/fmy/LLaVA-1.1.3/playground/data/llava_v1_5_mix665k.json \
    --image_folder /public/home/renwu04/fmy/LLaVA-1.1.3/playground/data \
    --vision_tower /public/home/renwu04/fmy/data/llava-v1.5-7b/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --mm_vision_select_feature 'cls_patch' \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-7b-Qformer-11-lora-finetune_from_vicuna-proto-mlp-2-4-layers-all-tokens_weight_task \
    --num_train_epochs 1 \
    --per_device_train_batch_size 5 \
    --per_device_eval_batch_size 8 \
    --gradient_accumulation_steps 12 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 100000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
